"""add_organization_slug

Revision ID: 492aba94cb0a
Revises: 85392bd488fc
Create Date: 2026-09-10 22:11:03.545544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '492aba94cb0a'
down_revision: Union[str, Sequence[str], None] = '85392bd488fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_logs', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('activity_logs', 'action',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('activity_logs', 'target',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_activity_logs_organization_id'), 'activity_logs', ['organization_id'], unique=False)
    op.drop_constraint(op.f('activity_logs_organization_id_fkey'), 'activity_logs', type_='foreignkey')
    op.drop_constraint(op.f('activity_logs_user_id_fkey'), 'activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'activity_logs', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'activity_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('api_keys', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('api_keys', 'key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('api_keys', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_api_keys_organization_id'), 'api_keys', ['organization_id'], unique=False)
    op.drop_constraint(op.f('api_keys_organization_id_fkey'), 'api_keys', type_='foreignkey')
    op.create_foreign_key(None, 'api_keys', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('clients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_clients_organization_id'), 'clients', ['organization_id'], unique=False)
    op.drop_constraint(op.f('clients_organization_id_fkey'), 'clients', type_='foreignkey')
    op.create_foreign_key(None, 'clients', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('expenses', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('expenses', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('expenses', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_expenses_organization_id'), 'expenses', ['organization_id'], unique=False)
    op.drop_constraint(op.f('expenses_organization_id_fkey'), 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('invoice_line_items', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invoice_line_items', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_invoice_line_items_invoice_id'), 'invoice_line_items', ['invoice_id'], unique=False)
    op.drop_constraint(op.f('invoice_line_items_invoice_id_fkey'), 'invoice_line_items', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_line_items', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.alter_column('invoices', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('invoices', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_invoices_client_id'), 'invoices', ['client_id'], unique=False)
    op.create_index(op.f('ix_invoices_organization_id'), 'invoices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_invoices_project_id'), 'invoices', ['project_id'], unique=False)
    op.drop_constraint(op.f('invoices_project_id_fkey'), 'invoices', type_='foreignkey')
    op.drop_constraint(op.f('invoices_client_id_fkey'), 'invoices', type_='foreignkey')
    op.drop_constraint(op.f('invoices_organization_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'invoices', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'invoices', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('organizations', 'slug',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('projects', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('projects', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_projects_client_id'), 'projects', ['client_id'], unique=False)
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.drop_constraint(op.f('projects_organization_id_fkey'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('projects_client_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'projects', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.alter_column('proposal_line_items', 'proposal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('proposal_line_items', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_proposal_line_items_proposal_id'), 'proposal_line_items', ['proposal_id'], unique=False)
    op.drop_constraint(op.f('proposal_line_items_proposal_id_fkey'), 'proposal_line_items', type_='foreignkey')
    op.create_foreign_key(None, 'proposal_line_items', 'proposals', ['proposal_id'], ['id'], ondelete='CASCADE')
    op.alter_column('proposals', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('proposals', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('proposals', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_proposals_client_id'), 'proposals', ['client_id'], unique=False)
    op.create_index(op.f('ix_proposals_organization_id'), 'proposals', ['organization_id'], unique=False)
    op.drop_constraint(op.f('proposals_organization_id_fkey'), 'proposals', type_='foreignkey')
    op.drop_constraint(op.f('proposals_client_id_fkey'), 'proposals', type_='foreignkey')
    op.create_foreign_key(None, 'proposals', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'proposals', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('subtasks', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subtasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_subtasks_task_id'), 'subtasks', ['task_id'], unique=False)
    op.drop_constraint(op.f('subtasks_task_id_fkey'), 'subtasks', type_='foreignkey')
    op.create_foreign_key(None, 'subtasks', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.alter_column('task_comments', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task_comments', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_task_comments_task_id'), 'task_comments', ['task_id'], unique=False)
    op.drop_constraint(op.f('task_comments_task_id_fkey'), 'task_comments', type_='foreignkey')
    op.drop_constraint(op.f('task_comments_user_id_fkey'), 'task_comments', type_='foreignkey')
    op.create_foreign_key(None, 'task_comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task_comments', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tasks', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tasks', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_tasks_organization_id'), 'tasks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.drop_constraint(op.f('tasks_assignee_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_project_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_organization_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    op.alter_column('time_logs', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('time_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('time_logs', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('time_logs', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_time_logs_organization_id'), 'time_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_time_logs_task_id'), 'time_logs', ['task_id'], unique=False)
    op.drop_constraint(op.f('time_logs_user_id_fkey'), 'time_logs', type_='foreignkey')
    op.drop_constraint(op.f('time_logs_organization_id_fkey'), 'time_logs', type_='foreignkey')
    op.drop_constraint(op.f('time_logs_task_id_fkey'), 'time_logs', type_='foreignkey')
    op.create_foreign_key(None, 'time_logs', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'time_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'time_logs', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('users_organization_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'otp_code')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'otp_expires_at')
    op.alter_column('webhooks', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('webhooks', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('webhooks', 'event_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_webhooks_organization_id'), 'webhooks', ['organization_id'], unique=False)
    op.drop_constraint(op.f('webhooks_organization_id_fkey'), 'webhooks', type_='foreignkey')
    op.create_foreign_key(None, 'webhooks', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhooks', type_='foreignkey')
    op.create_foreign_key(op.f('webhooks_organization_id_fkey'), 'webhooks', 'organizations', ['organization_id'], ['id'])
    op.drop_index(op.f('ix_webhooks_organization_id'), table_name='webhooks')
    op.alter_column('webhooks', 'event_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('webhooks', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('webhooks', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('otp_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('otp_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_organization_id_fkey'), 'users', 'organizations', ['organization_id'], ['id'])
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'time_logs', type_='foreignkey')
    op.drop_constraint(None, 'time_logs', type_='foreignkey')
    op.drop_constraint(None, 'time_logs', type_='foreignkey')
    op.create_foreign_key(op.f('time_logs_task_id_fkey'), 'time_logs', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(op.f('time_logs_organization_id_fkey'), 'time_logs', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(op.f('time_logs_user_id_fkey'), 'time_logs', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_time_logs_task_id'), table_name='time_logs')
    op.drop_index(op.f('ix_time_logs_organization_id'), table_name='time_logs')
    op.alter_column('time_logs', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('time_logs', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('time_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('time_logs', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_organization_id_fkey'), 'tasks', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(op.f('tasks_project_id_fkey'), 'tasks', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('tasks_assignee_id_fkey'), 'tasks', 'users', ['assignee_id'], ['id'])
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_organization_id'), table_name='tasks')
    op.alter_column('tasks', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tasks', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'task_comments', type_='foreignkey')
    op.drop_constraint(None, 'task_comments', type_='foreignkey')
    op.create_foreign_key(op.f('task_comments_user_id_fkey'), 'task_comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('task_comments_task_id_fkey'), 'task_comments', 'tasks', ['task_id'], ['id'])
    op.drop_index(op.f('ix_task_comments_task_id'), table_name='task_comments')
    op.alter_column('task_comments', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('task_comments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('task_comments', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'subtasks', type_='foreignkey')
    op.create_foreign_key(op.f('subtasks_task_id_fkey'), 'subtasks', 'tasks', ['task_id'], ['id'])
    op.drop_index(op.f('ix_subtasks_task_id'), table_name='subtasks')
    op.alter_column('subtasks', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subtasks', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'proposals', type_='foreignkey')
    op.drop_constraint(None, 'proposals', type_='foreignkey')
    op.create_foreign_key(op.f('proposals_client_id_fkey'), 'proposals', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(op.f('proposals_organization_id_fkey'), 'proposals', 'organizations', ['organization_id'], ['id'])
    op.drop_index(op.f('ix_proposals_organization_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_client_id'), table_name='proposals')
    op.alter_column('proposals', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('proposals', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('proposals', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'proposal_line_items', type_='foreignkey')
    op.create_foreign_key(op.f('proposal_line_items_proposal_id_fkey'), 'proposal_line_items', 'proposals', ['proposal_id'], ['id'])
    op.drop_index(op.f('ix_proposal_line_items_proposal_id'), table_name='proposal_line_items')
    op.alter_column('proposal_line_items', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('proposal_line_items', 'proposal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_client_id_fkey'), 'projects', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(op.f('projects_organization_id_fkey'), 'projects', 'organizations', ['organization_id'], ['id'])
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_client_id'), table_name='projects')
    op.alter_column('projects', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('projects', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('organizations', 'slug',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('organizations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_organization_id_fkey'), 'invoices', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(op.f('invoices_client_id_fkey'), 'invoices', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(op.f('invoices_project_id_fkey'), 'invoices', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_invoices_project_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_organization_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_client_id'), table_name='invoices')
    op.alter_column('invoices', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('invoices', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'invoice_line_items', type_='foreignkey')
    op.create_foreign_key(op.f('invoice_line_items_invoice_id_fkey'), 'invoice_line_items', 'invoices', ['invoice_id'], ['id'])
    op.drop_index(op.f('ix_invoice_line_items_invoice_id'), table_name='invoice_line_items')
    op.alter_column('invoice_line_items', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('invoice_line_items', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key(op.f('expenses_organization_id_fkey'), 'expenses', 'organizations', ['organization_id'], ['id'])
    op.drop_index(op.f('ix_expenses_organization_id'), table_name='expenses')
    op.alter_column('expenses', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('expenses', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('expenses', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.create_foreign_key(op.f('clients_organization_id_fkey'), 'clients', 'organizations', ['organization_id'], ['id'])
    op.drop_index(op.f('ix_clients_organization_id'), table_name='clients')
    op.alter_column('clients', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.create_foreign_key(op.f('api_keys_organization_id_fkey'), 'api_keys', 'organizations', ['organization_id'], ['id'])
    op.drop_index(op.f('ix_api_keys_organization_id'), table_name='api_keys')
    op.alter_column('api_keys', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('api_keys', 'key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('api_keys', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.create_foreign_key(op.f('activity_logs_user_id_fkey'), 'activity_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('activity_logs_organization_id_fkey'), 'activity_logs', 'organizations', ['organization_id'], ['id'])
    op.drop_index(op.f('ix_activity_logs_organization_id'), table_name='activity_logs')
    op.alter_column('activity_logs', 'target',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('activity_logs', 'action',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('activity_logs', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
