"""epic7_extensibility

Revision ID: 85392bd488fc
Revises: 97ff10720e95
Create Date: 2026-07-06 18:11:11.795036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85392bd488fc'
down_revision: Union[str, Sequence[str], None] = '97ff10720e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('portal_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_clients_portal_token'), 'clients', ['portal_token'], unique=True)
    op.add_column('organizations', sa.Column('brand_color', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('logo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'logo_url')
    op.drop_column('organizations', 'brand_color')
    op.drop_index(op.f('ix_clients_portal_token'), table_name='clients')
    op.drop_column('clients', 'portal_token')
    # ### end Alembic commands ###
