import { useParams } from 'react-router-dom';
import { useQuery, useMutation, useClient, gql } from 'urql';
import { 
  Loader2, 
  FileText, 
  Layout, 
  Download, 
  CheckCircle2, 
  XCircle, 
  Clock, 
  ExternalLink, 
  ShieldCheck, 
  Sparkles,
  ChevronRight,
  Briefcase,
  AlertCircle
} from 'lucide-react';
import { useState } from 'react';

const GET_PORTAL_DATA = gql`
  query GetPortalData($token: String!) {
    clientPortalData(token: $token) {
      organization {
        name
        brandColor
        logoUrl
      }
      currencyPreference
      client {
        id
        name
        email
        projects {
          id
          name
          description
          tasks {
            id
            title
            status
            priority
            issueType
          }
        }
        invoices {
          id
          amount
          status
          createdAt
        }
        proposals {
          id
          title
          description
          status
          createdAt
          lineItems {
            id
            description
            quantity
            unitPrice
          }
        }
      }
    }
  }
`;

const RESPOND_TO_PROPOSAL = gql`
  mutation RespondToProposal($token: String!, $proposalId: Int!, $accept: Boolean!) {
    respondToProposal(token: $token, proposalId: $proposalId, accept: $accept) {
      id
      status
    }
  }
`;

const GET_PORTAL_INVOICE_PDF = gql`
  query GetPortalInvoicePdf($token: String!, $id: Int!) {
    portalInvoicePdf(token: $token, id: $id)
  }
`;

const GET_PORTAL_PROPOSAL_PDF = gql`
  query GetPortalProposalPdf($token: String!, $id: Int!) {
    portalProposalPdf(token: $token, id: $id)
  }
`;

export default function ClientPortal() {
  const { token } = useParams();
  const [result, reexecuteQuery] = useQuery({ 
    query: GET_PORTAL_DATA, 
    variables: { token },
    requestPolicy: 'network-only'
  });

  const [, respondMutation] = useMutation(RESPOND_TO_PROPOSAL);
  const { data, fetching, error } = result;

  const [activeTab, setActiveTab] = useState('proposals');
  const [processingProposalId, setProcessingProposalId] = useState(null);
  const [downloadingId, setDownloadingId] = useState(null);
  const [actionSuccessMessage, setActionSuccessMessage] = useState(null);

  if (fetching) return (
    <div className="min-h-screen w-full flex items-center justify-center bg-[#f8fafc] text-slate-900 font-sans">
      <div className="flex flex-col items-center gap-4">
        <div className="w-12 h-12 rounded-2xl bg-indigo-50 border border-indigo-100 flex items-center justify-center animate-pulse shadow-sm">
          <Loader2 className="animate-spin text-indigo-600" size={24} />
        </div>
        <div className="text-center">
          <p className="text-sm font-bold tracking-wider text-slate-800 uppercase">Securing Connection</p>
          <p className="text-xs text-slate-500 mt-1">Loading your encrypted client portal...</p>
        </div>
      </div>
    </div>
  );

  if (error || !data?.clientPortalData) return (
    <div className="min-h-screen w-full flex items-center justify-center bg-[#f8fafc] text-slate-900 p-6 font-sans">
      <div className="max-w-md w-full bg-white border border-slate-200 rounded-3xl p-8 text-center shadow-xl">
        <div className="w-14 h-14 rounded-2xl bg-rose-50 border border-rose-200 flex items-center justify-center mx-auto mb-5 text-rose-600">
          <AlertCircle size={28} />
        </div>
        <h2 className="text-xl font-bold text-slate-900 mb-2">Access Denied or Link Expired</h2>
        <p className="text-sm text-slate-600 mb-6 leading-relaxed">
          The client portal security token is invalid or has been regenerated by the administrator. Please contact your account manager for an updated invitation link.
        </p>
        <div className="p-3 bg-slate-50 rounded-xl border border-slate-200 text-xs font-mono text-slate-500 break-all">
          Token: {token}
        </div>
      </div>
    </div>
  );

  const { organization, client, currencyPreference } = data.clientPortalData;
  const brandColor = organization.brandColor || '#4f46e5';

  const currencySymbols = {
    USD: '$',
    EUR: '€',
    GBP: '£',
    INR: '₹'
  };
  const symbol = currencySymbols[currencyPreference] || '$';

  const handleProposalAction = async (proposalId, accept) => {
    setProcessingProposalId(proposalId);
    try {
      const res = await respondMutation({ token, proposalId, accept });
      if (res.error) {
        alert(res.error.message);
      } else {
        setActionSuccessMessage(`Proposal successfully ${accept ? 'accepted! We are thrilled to partner with you.' : 'declined.'}`);
        setTimeout(() => setActionSuccessMessage(null), 6000);
        reexecuteQuery({ requestPolicy: 'network-only' });
      }
    } catch (err) {
      alert(err.message);
    } finally {
      setProcessingProposalId(null);
    }
  };

  const urqlClient = useClient();
  const API_BASE = import.meta.env.VITE_API_URL || (import.meta.env.VITE_GRAPHQL_URL ? import.meta.env.VITE_GRAPHQL_URL.replace(/\/graphql\/?$/, '') : 'http://localhost:8000');

  const handleDownloadInvoicePdf = async (invoiceId) => {
    setDownloadingId(`inv-${invoiceId}`);
    try {
      const res = await urqlClient.query(GET_PORTAL_INVOICE_PDF, { token, id: invoiceId }).toPromise();
      if (res.data?.portalInvoicePdf) {
        window.open(res.data.portalInvoicePdf, '_blank');
      } else {
        const cleanName = (client?.name || 'Client').replace(/\s+/g, '_');
        window.open(`${API_BASE}/static/Invoice_${String(invoiceId).padStart(4, '0')}_${cleanName}.pdf`, '_blank');
      }
    } catch (err) {
      console.error(err);
      const cleanName = (client?.name || 'Client').replace(/\s+/g, '_');
      window.open(`${API_BASE}/static/Invoice_${String(invoiceId).padStart(4, '0')}_${cleanName}.pdf`, '_blank');
    } finally {
      setDownloadingId(null);
    }
  };

  const handleDownloadProposalPdf = async (proposalId) => {
    setDownloadingId(`prop-${proposalId}`);
    try {
      const res = await urqlClient.query(GET_PORTAL_PROPOSAL_PDF, { token, id: proposalId }).toPromise();
      if (res.data?.portalProposalPdf) {
        window.open(res.data.portalProposalPdf, '_blank');
      } else {
        const cleanName = (client?.name || 'Client').replace(/\s+/g, '_');
        window.open(`${API_BASE}/static/Proposal_${proposalId}_${cleanName}.pdf`, '_blank');
      }
    } catch (err) {
      console.error(err);
      const cleanName = (client?.name || 'Client').replace(/\s+/g, '_');
      window.open(`${API_BASE}/static/Proposal_${proposalId}_${cleanName}.pdf`, '_blank');
    } finally {
      setDownloadingId(null);
    }
  };

  const proposals = client.proposals || [];
  const invoices = client.invoices || [];
  const projects = client.projects || [];

  return (
    <div className="min-h-screen bg-[#f8fafc] text-slate-900 font-sans flex flex-col selection:bg-indigo-500/20 selection:text-indigo-900">
      {/* Top Ambient Light Banner */}
      <div 
        className="w-full h-1.5 transition-colors duration-500" 
        style={{ backgroundColor: brandColor }} 
      />

      {/* Enterprise Header */}
      <header className="border-b border-slate-200/80 bg-white/95 backdrop-blur-xl sticky top-0 z-30 px-6 py-4 shadow-xs">
        <div className="max-w-6xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-4">
            {organization.logoUrl ? (
              <img 
                src={organization.logoUrl} 
                alt={organization.name} 
                className="h-10 w-auto max-w-[120px] object-contain rounded-xl bg-slate-50 border border-slate-200 p-1 shadow-2xs" 
              />
            ) : (
              <div 
                className="w-10 h-10 rounded-xl flex items-center justify-center font-bold text-white shadow-sm text-lg"
                style={{ backgroundColor: brandColor }}
              >
                {organization.name.charAt(0)}
              </div>
            )}
            <div>
              <div className="flex items-center gap-2">
                <h1 className="text-base font-bold text-slate-900 tracking-tight">{organization.name}</h1>
                <span className="inline-flex items-center gap-1 text-[10px] font-semibold px-2 py-0.5 rounded-full bg-emerald-50 text-emerald-700 border border-emerald-200">
                  <ShieldCheck size={10} /> Verified Portal
                </span>
              </div>
              <p className="text-xs text-slate-500 font-medium">Client Collaborative Workspace</p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <div className="text-right hidden sm:block">
              <p className="text-xs text-slate-400 font-medium">Authenticated Client</p>
              <p className="text-sm font-semibold text-slate-800">{client.name}</p>
            </div>
            <div 
              className="w-9 h-9 rounded-full bg-slate-100 border border-slate-200 flex items-center justify-center text-xs font-bold text-slate-700 shadow-2xs"
              title={client.email}
            >
              {client.name.charAt(0)}
            </div>
          </div>
        </div>
      </header>

      {/* Success Notification */}
      {actionSuccessMessage && (
        <div className="max-w-6xl mx-auto w-full px-6 pt-6 animate-in fade-in slide-in-from-top-2 duration-300">
          <div className="p-4 rounded-2xl bg-emerald-50 border border-emerald-200 flex items-center gap-3 text-emerald-800 text-sm shadow-xs">
            <CheckCircle2 size={18} className="text-emerald-600 shrink-0" />
            <span className="font-semibold">{actionSuccessMessage}</span>
          </div>
        </div>
      )}

      {/* Portal Body */}
      <main className="flex-1 max-w-6xl w-full mx-auto p-4 sm:p-6 md:p-8 flex flex-col md:flex-row gap-6">
        {/* Navigation Sidebar */}
        <aside className="w-full md:w-64 shrink-0 flex md:flex-col gap-2 overflow-x-auto pb-2 md:pb-0">
          <PortalNav 
            active={activeTab === 'proposals'} 
            onClick={() => setActiveTab('proposals')} 
            icon={<Sparkles size={18}/>} 
            label="Proposals" 
            badge={proposals.length > 0 ? proposals.length : null}
            brandColor={brandColor} 
          />
          <PortalNav 
            active={activeTab === 'projects'} 
            onClick={() => setActiveTab('projects')} 
            icon={<Layout size={18}/>} 
            label="Deliverables" 
            badge={projects.length > 0 ? projects.length : null}
            brandColor={brandColor} 
          />
          <PortalNav 
            active={activeTab === 'invoices'} 
            onClick={() => setActiveTab('invoices')} 
            icon={<FileText size={18}/>} 
            label="Invoices" 
            badge={invoices.length > 0 ? invoices.length : null}
            brandColor={brandColor} 
          />
        </aside>

        {/* Content Pane */}
        <div className="flex-1 bg-white border border-slate-200/90 rounded-3xl p-5 sm:p-7 shadow-xs min-h-[560px]">
          
          {/* TAB 1: PROPOSALS */}
          {activeTab === 'proposals' && (
            <div>
              <div className="flex items-center justify-between pb-6 mb-6 border-b border-slate-200">
                <div>
                  <h2 className="text-xl font-bold text-slate-900 tracking-tight">Proposals & SOWs</h2>
                  <p className="text-xs text-slate-500 mt-1">Review project scope, pricing terms, and accept or decline agreements.</p>
                </div>
                <span className="text-xs font-mono text-slate-600 bg-slate-100 px-3 py-1 rounded-full border border-slate-200 font-semibold">
                  {proposals.length} Total
                </span>
              </div>

              {proposals.length === 0 ? (
                <div className="py-20 text-center flex flex-col items-center">
                  <div className="w-14 h-14 rounded-2xl bg-slate-100 border border-slate-200 flex items-center justify-center text-slate-400 mb-4">
                    <Sparkles size={24} />
                  </div>
                  <p className="text-base font-semibold text-slate-800">No proposals available</p>
                  <p className="text-xs text-slate-500 mt-1 max-w-sm">When your project proposal or statement of work is ready, it will appear here for one-click review and signature.</p>
                </div>
              ) : (
                <div className="space-y-6">
                  {proposals.map((prop) => {
                    const totalAmount = (prop.lineItems || []).reduce((sum, item) => sum + (item.quantity * item.unitPrice), 0);
                    const isPending = prop.status === 'Sent' || prop.status === 'Draft';
                    const isAccepted = prop.status === 'Accepted';
                    const isDeclined = prop.status === 'Declined';

                    return (
                      <div 
                        key={prop.id} 
                        className="bg-slate-50/70 border border-slate-200/90 rounded-2xl p-6 hover:border-slate-300 transition-all duration-200 shadow-2xs"
                      >
                        <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4 pb-5 border-b border-slate-200/80">
                          <div>
                            <div className="flex items-center gap-3">
                              <h3 className="text-lg font-bold text-slate-900">{prop.title}</h3>
                              <span className={`text-[11px] font-bold uppercase tracking-wider px-2.5 py-0.5 rounded-full border ${
                                isAccepted ? 'bg-emerald-50 text-emerald-700 border-emerald-200' :
                                isDeclined ? 'bg-rose-50 text-rose-700 border-rose-200' :
                                'bg-amber-50 text-amber-700 border-amber-200'
                              }`}>
                                {prop.status}
                              </span>
                            </div>
                            <p className="text-xs text-slate-500 mt-1">
                              Issued {prop.createdAt ? new Date(prop.createdAt).toLocaleDateString(undefined, { dateStyle: 'medium' }) : 'Recently'}
                            </p>
                          </div>

                          <div className="flex items-baseline gap-2">
                            <span className="text-xs text-slate-500 font-medium">Total Investment:</span>
                            <span className="text-xl font-black text-slate-900">{symbol}{totalAmount.toLocaleString(undefined, { minimumFractionDigits: 2 })}</span>
                          </div>
                        </div>

                        {prop.description && (
                          <div className="py-4 text-xs text-slate-700 leading-relaxed border-b border-slate-200/80">
                            <span className="font-semibold text-slate-400 uppercase tracking-wider text-[10px] block mb-1">Scope & Objectives:</span>
                            {prop.description}
                          </div>
                        )}

                        {/* Line Items Table */}
                        {prop.lineItems && prop.lineItems.length > 0 && (
                          <div className="py-4 border-b border-slate-200/80 overflow-x-auto">
                            <table className="w-full text-left text-xs">
                              <thead>
                                <tr className="text-slate-400 uppercase tracking-wider text-[10px] border-b border-slate-200 pb-2">
                                  <th className="font-semibold pb-2">Deliverable / Milestone</th>
                                  <th className="font-semibold text-right pb-2">Qty</th>
                                  <th className="font-semibold text-right pb-2">Rate</th>
                                  <th className="font-semibold text-right pb-2">Amount</th>
                                </tr>
                              </thead>
                              <tbody className="divide-y divide-slate-200/60">
                                {prop.lineItems.map((item) => (
                                  <tr key={item.id} className="text-slate-700">
                                    <td className="py-2.5 pr-4 font-medium text-slate-900">{item.description}</td>
                                    <td className="py-2.5 text-right font-mono text-slate-500">{item.quantity}</td>
                                    <td className="py-2.5 text-right font-mono text-slate-500">{symbol}{item.unitPrice.toLocaleString(undefined, { minimumFractionDigits: 2 })}</td>
                                    <td className="py-2.5 text-right font-mono font-bold text-slate-900">{symbol}{(item.quantity * item.unitPrice).toLocaleString(undefined, { minimumFractionDigits: 2 })}</td>
                                  </tr>
                                ))}
                              </tbody>
                            </table>
                          </div>
                        )}

                        {/* Actions Footer */}
                        <div className="pt-5 flex flex-wrap items-center justify-between gap-4">
                          <button
                            onClick={() => handleDownloadProposalPdf(prop.id)}
                            disabled={downloadingId === `prop-${prop.id}`}
                            className="inline-flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-semibold bg-white hover:bg-slate-100 text-slate-700 border border-slate-200 shadow-2xs transition-colors cursor-pointer"
                          >
                            <Download size={14} />
                            <span>{downloadingId === `prop-${prop.id}` ? 'Opening PDF...' : 'Download PDF Proposal'}</span>
                          </button>

                          {isPending && (
                            <div className="flex items-center gap-3">
                              <button
                                onClick={() => handleProposalAction(prop.id, false)}
                                disabled={processingProposalId === prop.id}
                                className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl text-xs font-semibold bg-rose-50 hover:bg-rose-100 text-rose-700 border border-rose-200 transition-colors cursor-pointer"
                              >
                                <XCircle size={14} />
                                <span>Decline</span>
                              </button>
                              <button
                                onClick={() => handleProposalAction(prop.id, true)}
                                disabled={processingProposalId === prop.id}
                                style={{ backgroundColor: brandColor }}
                                className="inline-flex items-center gap-1.5 px-5 py-2 rounded-xl text-xs font-bold text-white shadow-sm hover:opacity-95 transition-opacity cursor-pointer"
                              >
                                {processingProposalId === prop.id ? (
                                  <Loader2 size={14} className="animate-spin" />
                                ) : (
                                  <CheckCircle2 size={14} />
                                )}
                                <span>Accept & Sign Proposal</span>
                              </button>
                            </div>
                          )}

                          {isAccepted && (
                            <div className="flex items-center gap-1.5 text-xs text-emerald-700 font-semibold bg-emerald-50 px-3 py-1.5 rounded-xl border border-emerald-200">
                              <CheckCircle2 size={15} className="text-emerald-600" />
                              <span>Agreement accepted & confirmed</span>
                            </div>
                          )}

                          {isDeclined && (
                            <div className="flex items-center gap-1.5 text-xs text-rose-700 font-semibold bg-rose-50 px-3 py-1.5 rounded-xl border border-rose-200">
                              <XCircle size={15} className="text-rose-600" />
                              <span>Proposal was declined</span>
                            </div>
                          )}
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          )}

          {/* TAB 2: DELIVERABLES & PROJECTS */}
          {activeTab === 'projects' && (
            <div>
              <div className="flex items-center justify-between pb-6 mb-6 border-b border-slate-200">
                <div>
                  <h2 className="text-xl font-bold text-slate-900 tracking-tight">Active Deliverables</h2>
                  <p className="text-xs text-slate-500 mt-1">Real-time status of your deliverables, milestones, and task progression.</p>
                </div>
                <span className="text-xs font-mono text-slate-600 bg-slate-100 px-3 py-1 rounded-full border border-slate-200 font-semibold">
                  {projects.length} Project{projects.length !== 1 ? 's' : ''}
                </span>
              </div>

              {projects.length === 0 ? (
                <div className="py-20 text-center flex flex-col items-center">
                  <div className="w-14 h-14 rounded-2xl bg-slate-100 border border-slate-200 flex items-center justify-center text-slate-400 mb-4">
                    <Layout size={24} />
                  </div>
                  <p className="text-base font-semibold text-slate-800">No deliverables tracked yet</p>
                  <p className="text-xs text-slate-500 mt-1 max-w-sm">Once a project commences, sprint tasks and live deliverable milestones will be synchronized here.</p>
                </div>
              ) : (
                <div className="space-y-10">
                  {projects.map((project) => {
                    const tasks = project.tasks || [];
                    const doneCount = tasks.filter(t => t.status === 'done').length;
                    const percent = tasks.length > 0 ? Math.round((doneCount / tasks.length) * 100) : 0;

                    return (
                      <div key={project.id} className="bg-slate-50/70 border border-slate-200/90 rounded-2xl p-6 shadow-2xs">
                        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 border-b border-slate-200/80">
                          <div>
                            <div className="flex items-center gap-3">
                              <h3 className="text-lg font-bold text-slate-900">{project.name}</h3>
                              <span className="text-[10px] font-mono font-semibold px-2 py-0.5 rounded bg-indigo-50 text-indigo-700 border border-indigo-200">
                                {tasks.length} Tasks
                              </span>
                            </div>
                            {project.description && (
                              <p className="text-xs text-slate-600 mt-1 max-w-2xl leading-relaxed">{project.description}</p>
                            )}
                          </div>

                          {/* Deliverable Progress Gauge */}
                          <div className="sm:text-right shrink-0">
                            <div className="flex items-center gap-2 mb-1.5 sm:justify-end">
                              <span className="text-xs font-semibold text-slate-800">{percent}% Completed</span>
                              <span className="text-[10px] text-slate-500 font-medium">({doneCount}/{tasks.length})</span>
                            </div>
                            <div className="w-44 h-2 rounded-full bg-slate-200 overflow-hidden">
                              <div 
                                className="h-full rounded-full transition-all duration-500"
                                style={{ 
                                  width: `${percent}%`,
                                  backgroundColor: brandColor 
                                }}
                              />
                            </div>
                          </div>
                        </div>

                        {/* Kanban Columns */}
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-6">
                          {[
                            { key: 'todo', label: 'Upcoming / Backlog', color: 'text-slate-700' },
                            { key: 'in_progress', label: 'In Execution', color: 'text-sky-700' },
                            { key: 'done', label: 'Ready & Completed', color: 'text-emerald-700' }
                          ].map(col => {
                            const colTasks = tasks.filter(t => t.status === col.key);
                            return (
                              <div key={col.key} className="bg-white border border-slate-200/90 rounded-xl p-3 flex flex-col shadow-2xs">
                                <div className="flex items-center justify-between pb-3 mb-3 border-b border-slate-100">
                                  <span className={`text-[11px] font-bold uppercase tracking-wider ${col.color}`}>
                                    {col.label}
                                  </span>
                                  <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-slate-100 text-slate-600 border border-slate-200">
                                    {colTasks.length}
                                  </span>
                                </div>

                                <div className="space-y-2.5 flex-1 min-h-[140px]">
                                  {colTasks.length === 0 ? (
                                    <div className="h-full flex items-center justify-center p-4 border border-dashed border-slate-200 rounded-lg text-slate-400 text-[11px]">
                                      No items
                                    </div>
                                  ) : (
                                    colTasks.map(task => (
                                      <div key={task.id} className="bg-slate-50/80 p-3 rounded-lg border border-slate-200 hover:border-slate-300 transition-colors shadow-2xs">
                                        <p className="font-semibold text-xs text-slate-900">{task.title}</p>
                                        <div className="flex items-center gap-2 mt-2.5">
                                          <span className="text-[9px] font-mono uppercase font-bold tracking-wider px-1.5 py-0.5 rounded bg-slate-100 text-slate-600 border border-slate-200">
                                            {task.issueType || 'Task'}
                                          </span>
                                          <span className={`text-[9px] font-mono uppercase font-bold tracking-wider px-1.5 py-0.5 rounded border ${
                                            task.priority === 'High' ? 'bg-rose-50 text-rose-700 border-rose-200' :
                                            task.priority === 'Medium' ? 'bg-amber-50 text-amber-700 border-amber-200' :
                                            'bg-slate-100 text-slate-600 border-slate-200'
                                          }`}>
                                            {task.priority || 'Normal'}
                                          </span>
                                        </div>
                                      </div>
                                    ))
                                  )}
                                </div>
                              </div>
                            );
                          })}
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          )}

          {/* TAB 3: INVOICES */}
          {activeTab === 'invoices' && (
            <div>
              <div className="flex items-center justify-between pb-6 mb-6 border-b border-slate-200">
                <div>
                  <h2 className="text-xl font-bold text-slate-900 tracking-tight">Billing & Invoices</h2>
                  <p className="text-xs text-slate-500 mt-1">Review transaction statements, payment records, and official PDF invoices.</p>
                </div>
                <span className="text-xs font-mono text-slate-600 bg-slate-100 px-3 py-1 rounded-full border border-slate-200 font-semibold">
                  {invoices.length} Total
                </span>
              </div>

              {invoices.length === 0 ? (
                <div className="py-20 text-center flex flex-col items-center">
                  <div className="w-14 h-14 rounded-2xl bg-slate-100 border border-slate-200 flex items-center justify-center text-slate-400 mb-4">
                    <FileText size={24} />
                  </div>
                  <p className="text-base font-semibold text-slate-800">No invoices issued</p>
                  <p className="text-xs text-slate-500 mt-1 max-w-sm">When invoices are issued for billable work, you can review and download them here.</p>
                </div>
              ) : (
                <div className="space-y-4">
                  {invoices.map((inv) => {
                    const isPaid = inv.status === 'Paid';
                    return (
                      <div 
                        key={inv.id} 
                        className="bg-slate-50/70 border border-slate-200/90 rounded-2xl p-5 hover:border-slate-300 transition-all flex flex-col sm:flex-row sm:items-center justify-between gap-4 shadow-2xs"
                      >
                        <div className="flex items-center gap-4">
                          <div className={`w-11 h-11 rounded-xl flex items-center justify-center shrink-0 border ${
                            isPaid ? 'bg-emerald-50 text-emerald-700 border-emerald-200' : 'bg-amber-50 text-amber-700 border-amber-200'
                          }`}>
                            <FileText size={20} />
                          </div>
                          <div>
                            <div className="flex items-center gap-2">
                              <h3 className="text-base font-bold text-slate-900">Invoice #{String(inv.id).padStart(4, '0')}</h3>
                              <span className={`text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full border ${
                                isPaid ? 'bg-emerald-50 text-emerald-700 border-emerald-200' : 'bg-amber-50 text-amber-700 border-amber-200'
                              }`}>
                                {inv.status}
                              </span>
                            </div>
                            <p className="text-xs text-slate-500 mt-0.5">
                              Issued {inv.createdAt ? new Date(inv.createdAt).toLocaleDateString(undefined, { dateStyle: 'medium' }) : 'Recently'}
                            </p>
                          </div>
                        </div>

                        <div className="flex items-center justify-between sm:justify-end gap-5 border-t sm:border-0 border-slate-200 pt-3 sm:pt-0">
                          <div className="sm:text-right">
                            <span className="text-[10px] uppercase font-semibold text-slate-500 block">Amount</span>
                            <span className="text-lg font-black text-slate-900">{symbol}{inv.amount.toLocaleString(undefined, { minimumFractionDigits: 2 })}</span>
                          </div>

                          <div className="flex items-center gap-2">
                            <button
                              onClick={() => handleDownloadInvoicePdf(inv.id)}
                              disabled={downloadingId === `inv-${inv.id}`}
                              className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-semibold bg-white hover:bg-slate-100 text-slate-700 border border-slate-200 shadow-2xs transition-colors cursor-pointer"
                              title="Download PDF Invoice"
                            >
                              <Download size={14} />
                              <span className="hidden sm:inline">{downloadingId === `inv-${inv.id}` ? 'Loading...' : 'PDF'}</span>
                            </button>

                            {!isPaid && (
                              <button 
                                style={{ backgroundColor: brandColor }}
                                onClick={() => alert(`Payment instructions for invoice #${inv.id}: Please remit ${symbol}${inv.amount.toFixed(2)} via standard wire or bank transfer specified in the PDF invoice.`)}
                                className="px-4 py-2 rounded-xl text-xs font-bold text-white shadow-sm hover:opacity-90 transition-opacity cursor-pointer"
                              >
                                Pay Now
                              </button>
                            )}
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          )}

        </div>
      </main>

      {/* Subtle White-label Footer */}
      <footer className="border-t border-slate-200/80 py-6 text-center text-xs text-slate-500 bg-white/60">
        <div className="max-w-6xl mx-auto px-6 flex flex-col sm:flex-row items-center justify-between gap-2">
          <span>&copy; {new Date().getFullYear()} {organization.name}. All rights reserved.</span>
          <span className="text-[11px] text-slate-400">Encrypted B2B Client Portal &bull; Enterprise Grade</span>
        </div>
      </footer>
    </div>
  );
}

function PortalNav({ active, onClick, icon, label, badge, brandColor }) {
  return (
    <button
      onClick={onClick}
      style={{
        backgroundColor: active ? `${brandColor}14` : 'transparent',
        borderColor: active ? `${brandColor}40` : 'transparent',
        color: active ? brandColor : undefined
      }}
      className={`flex-1 md:w-full flex items-center justify-between px-4 py-3 rounded-2xl font-medium transition-all text-xs sm:text-sm border whitespace-nowrap cursor-pointer ${
        active 
          ? 'shadow-xs font-bold' 
          : 'text-slate-600 hover:text-slate-900 hover:bg-slate-100/80 border-transparent'
      }`}
    >
      <div className="flex items-center gap-3">
        <span style={{ color: active ? brandColor : undefined }} className="text-slate-400">
          {icon}
        </span>
        <span className={active ? 'text-slate-900 font-bold' : 'text-slate-600'}>{label}</span>
      </div>
      {badge !== null && (
        <span 
          style={{ 
            backgroundColor: active ? brandColor : undefined,
            color: active ? '#ffffff' : undefined 
          }}
          className={`text-[10px] font-mono font-bold px-2 py-0.5 rounded-full ${
            active ? 'shadow-xs' : 'bg-slate-100 text-slate-600 border border-slate-200/80'
          }`}
        >
          {badge}
        </span>
      )}
    </button>
  );
}
